behaviors:
  AgenteCoche:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 2048000
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      normalize: true
      learning_rate_schedule: linear
      behavioral_cloning:
        demo_path: Demos/DemoCarrera_0.demo
        steps: 5000
        strength: 0.5
    reward_signals:
      gail:
        gamma: 0.99
        encoding_size: 128
        strength: 1
        demo_path: Demos/DemoCarrera_0.demo
    
    max_steps: 500000
    time_horizon: 64
    summary_freq: 100000