behaviors:
  AgenteCoche:
    trainer_type: ppo
    hyperparameters:
      normalize: true
      num_epoch: 3
      time_horizon: 1000
      batch_size: 2024
      buffer_size: 20240
      max_steps: 1000000
      summary_freq: 3000
      num_layers: 3
      hidden_units: 512
      behavioral_cloning:
        demo_path: Project/Assets/ML-Agents/Examples/Crawler/Demos/ExpertCrawlerSta.demo
        strength: 0.5
        steps: 5000
      reward_signals:
        gail:
          strength: 1
          gamma: 0.99
          encoding_size: 128
          demo_path: Project/Assets/ML-Agents/Examples/Crawler/Demos/ExpertCrawlerSta.demo
