behaviors:
  AgenteCoche:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.00005
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.1
      gail:
        gamma: 0.99
        strength: 1
        demo_path: DemosRecta/Recta_2.demo
    behavioral_cloning:
        strength: 1
        demo_path: DemosRecta/Recta_2.demo
    keep_checkpoints: 5
    max_steps: 500000000
    time_horizon: 1000
    summary_freq: 50000
    threaded: true